name: notes
description: Notes
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0
  sqflite: ^2.2.4+1
  path_provider: ^2.0.12
  flutter_slidable: ^2.0.0
  intl: ^0.18.0
  image_picker: ^0.8.6+1
  flutter_calendar_carousel: ^2.4.2
  cupertino_icons: ^1.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
uses-material-design: true